Fixed bug 3885 - smpeg2 fails build if USE_SYSTEM_THREAD is defined
Ozkan Sezer

smpeg2 in SDL_mixer fails build if USE_SYSTEM_THREAD is defined:

MPEGsystem.cpp: In constructor ?MPEGsystem::MPEGsystem(SDL_RWops*)?:
MPEGsystem.cpp:443: error: cannot convert ?MPEGsystem* const? to ?const char*? for argument ?2? to ?SDL_Thread* SDL_CreateThread(int (*)(void*), const char*, void*)?
MPEGsystem.cpp: In member function ?virtual void MPEGsystem::Start()?:
MPEGsystem.cpp:1251: error: cannot convert ?MPEGsystem* const? to ?const char*? for argument ?2? to ?SDL_Thread* SDL_CreateThread(int (*)(void*), const char*, void*)?

The thread name parameter to SDL_CreateThread() is missing in the two calls.